# code: language=ansible

# Search for suggested NS to backup
trilio_kubernetes_suggest: true
# Auto create NS Backup Plan
trilio_kubernetes_autoprotect: true
# List of NS to exclude
trilio_kubernetes_autoprotect_exclude: ['openshift-storage', 'openshift-operators']

# app yaml to deploy
trilio_kubernetes_deploy_demo_app: false
trilio_kubernetes_namespace: my-vm-namespace

#
# Backup Target
#
# Currently assumes AWS S3
# IMPORTANT: See templates/target.yaml.j2 to modify for other targets
# TODO: Specify NFS or S3
trilio_kubernetes_create_target: true
trilio_kubernetes_target_type: S3
trilio_kubernetes_target_name: vm-backup-target
trilio_kubernetes_s3_bucket_name: tvk-migration-demo1
trilio_kubernetes_s3_region: us-east-1
trilio_kubernetes_s3_threshold_capacity: 100Gi
trilio_kubernetes_secret_name: s3-access-secret

#
# Backup Plan Details
# Note this must be relevant to the test/demo app
#
trilio_kubernetes_create_backupplan: true
trilio_kubernetes_backupplan_name: vm-backupplan
trilio_kubernetes_backupplan_type: ns # ns|label|operator
trilio_kubernetes_backup_match_label: "app: k8s-demo-app" # ignored for ns backup type

#
# Perform Backup
trilio_kubernetes_backup_prefix: "{{ trilio_kubernetes_backupplan_name }}"
trilio_kubernetes_backup_type: Full # Full | Incremental
