# code: language=ansible

# Set of tasks for creating a Trilio for Kubernetes Backup Plan in a namespace
# for describing what and where to backup
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Backup Plan Tasks
  tags: ['backup', 'backupplan', 'smoketest', 'autoprotect']
  block:
    - name: Configure the backup plan in {{ trilio_kubernetes_namespace_create }}
      ansible.builtin.template:
        src: templates/backupplan.yaml.j2
        dest: /tmp/{{ trilio_kubernetes_backupplan_name }}-backupplan.yaml
        mode: "0600"

    # Create the specified backup plan in specifed namespace
    - name: Create the backup plan "{{ trilio_kubernetes_backupplan_name }}"
      kubernetes.core.k8s:
        api_key: "{{ trilio_kubernetes_auth_results.k8s_auth.api_key }}"
        host: "{{ trilio_kubernetes_host }}"
        kind: BackupPlan
        state: present
        namespace: "{{ trilio_kubernetes_namespace_create }}"
        src: "/tmp/{{ trilio_kubernetes_backupplan_name }}-backupplan.yaml"
        validate_certs: false
      register: trilio_kubernetes_backupplan
      when: trilio_kubernetes_auth_type == "password"

    - name: Wait for the backup plan to be created "{{ trilio_kubernetes_backupplan_name }}"
      ansible.builtin.shell: |
        oc login "{{ trilio_kubernetes_auth_api }}" --token="{{ trilio_kubernetes_auth_results.openshift_auth.api_key }}" \
          --insecure-skip-tls-verify=true 2>&/dev/null
        oc get backupplans/"{{ trilio_kubernetes_backupplan_name }}" -n {{ trilio_kubernetes_namespace_create }}
      register: trilio_kubernetes_backupplan_available
      retries: 5
      delay: 10
      until: trilio_kubernetes_backupplan_available.stdout.find("Available") != -1
      ignore_errors: true
      when:
        - trilio_kubernetes_auth_type == "password"
        - trilio_kubernetes_distro == "openshift"
        - trilio_kubernetes_cli | bool

    - name: Show backup plan created output
      ansible.builtin.debug:
        var: trilio_kubernetes_backupplan_available.stdout_lines
