# code: language=ansible

# Set of tasks for creating a Trilio for Kubernetes Backup where auth is password
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Execute Backup Tasks
  tags: ['backup', 'backupplan', 'smoketest', 'autoprotect']
  block:
    - name: Set backup name
      ansible.builtin.set_fact:
        trilio_kubernetes_backup_name: "{{ trilio_kubernetes_backupplan_name_var }}-{{ ansible_date_time.date }}-{{ ansible_date_time.epoch }}"

    - name: Configure the backup using {{ trilio_kubernetes_backupplan_name_var }}
      ansible.builtin.template:
        src: templates/backup.yaml.j2
        dest: /tmp/{{ trilio_kubernetes_backupplan_name_var }}-backup.yaml
        mode: "0600"

    # Create the specified backup plan in specifed namespace
    - name: Execute the backup of {{ trilio_kubernetes_backupplan_name_var }}
      kubernetes.core.k8s:
        api_key: "{{ trilio_kubernetes_auth_results.openshift_auth.api_key }}"
        host: "{{ trilio_kubernetes_host }}"
        kind: Backup
        state: present
        namespace: "{{ trilio_kubernetes_namespace_var }}"
        src: "/tmp/{{ trilio_kubernetes_backupplan_name_var }}-backup.yaml"
        validate_certs: false
      register: trilio_kubernetes_backup

    - name: Wait for backup of {{ trilio_kubernetes_backupplan_name_var }}
      ansible.builtin.shell: |
        oc login "{{ trilio_kubernetes_auth_api }}" --token="{{ trilio_kubernetes_auth_results.openshift_auth.api_key }}" \
          --insecure-skip-tls-verify=true 2>&/dev/null
        oc get backups/{{ trilio_kubernetes_backup_name }} -n {{ trilio_kubernetes_namespace_var }}
      register: trilio_kubernetes_backup_available
      retries: "{{ trilio_kubernetes_backup_polling_retries }}"
      delay: "{{ trilio_kubernetes_backup_polling_every_seconds }}"
      until: trilio_kubernetes_backup_available.stdout.find("Available") != -1
      ignore_errors: true
      when:
        - trilio_kubernetes_auth_type == "password"
        - trilio_kubernetes_distro == "openshift"
        - trilio_kubernetes_cli | bool
      changed_when: trilio_kubernetes_backup_available.rc != 0

    - name: Show backup created output
      ansible.builtin.debug:
        var: trilio_kubernetes_backup_available.stdout_lines
