# code: language=ansible

# Set of tasks for creating performing a Trilio for Kubernetes Restore when using password auth
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Prepare Continuous Restore Tasks
  tags: ['restore']
  block:
    - name: Identify Continuous Restore Policy for {{ trilio_kubernetes_restore_namespace }}
      when:
        - trilio_kubernetes_auth_type == "password"
        - trilio_kubernetes_distro == "openshift"
        - trilio_kubernetes_cli | bool
      ansible.builtin.shell: |
        set -o pipefail
        oc login "{{ trilio_kubernetes_auth_api }}" --token="{{ trilio_kubernetes_auth_results.openshift_auth.api_key }}" \
          --insecure-skip-tls-verify=true 2>&/dev/null
        oc get continuousrestoreplan.triliovault.trilio.io | awk "/Available/ \{print $1\}"" | while read CRP
        do
          CRP_MATCH=$(oc get continuousrestoreplan.triliovault.trilio.io/$CRP -o yaml |
            grep "{{ trilio_kubernetes_restore_namespace }}/{{ trilio_kubernetes_cr_backupplan }})
          if [[ -n "$CRP_MATCH" ]]
          then
            echo "$CRP"
            break
          fi
        done
      register: trilio_kubernetes_continuous_restore_policy
      changed_when: trilio_kubernetes_continuous_restore_policy.rc != 0

    - name: Show CR Policy output
      ansible.builtin.debug:
        var: continuous_restore_policy.stdout_lines
