# code: language=ansible
# Set of tasks that will authenticate to OpenShift
# User can use kubeconfig or user/pass
# If a user is authenticating using username/password:
# Create an encrypted vault file with the following format
# trilio_kubernetes_username:
# trilio_kubernetes_password:
# Pass this encrypted vault file on the ansible command line
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Kubernetes Authentication
  tags: ['always', 'auth', 'smoketest', 'migrate']
  block:
    - name: Check Kubeconfig is available
      when: trilio_kubernetes_auth_type == 'kubeconfig'
      ansible.builtin.stat:
        path: "{{ trilio_kubernetes_kubeconfig }}"
