# code: language=ansible

# Set of tasks for creating a Trilio for Kubernetes Backup Plan in a namespace
# for describing what and where to backup
#
# Authors: Kevin Jackson <kevin.jackson at trilio io>

- name: Create Backup Plan Tasks
  tags: ['backup', 'backupplan', 'smoketest', 'autoprotect']
  block:
    - name: Configure the backup plan in {{ trilio_kubernetes_namespace_var }}
      ansible.builtin.template:
        src: templates/backupplan.yaml.j2
        dest: /tmp/{{ trilio_kubernetes_backupplan_name_var }}-backupplan.yaml
        mode: "0600"

    # Create the specified backup plan in specifed namespace
    - name: Create the backup plan "{{ trilio_kubernetes_backupplan_name_var }}"
      kubernetes.core.k8s:
        api_key: "{{ trilio_kubernetes_auth_results.k8s_auth.api_key }}"
        host: "{{ trilio_kubernetes_host }}"
        kind: BackupPlan
        state: present
        namespace: "{{ trilio_kubernetes_namespace_var }}"
        src: "/tmp/{{ trilio_kubernetes_backupplan_name_var }}-backupplan.yaml"
        validate_certs: false
      register: trilio_kubernetes_backupplan
      when: trilio_kubernetes_auth_type == "password"

    - name: Wait for the backup plan to be created "{{ trilio_kubernetes_backupplan_name_var }}"
      ansible.builtin.shell: |
        oc login "{{ trilio_kubernetes_auth_api }}" --token="{{ trilio_kubernetes_auth_results.openshift_auth.api_key }}" \
          --insecure-skip-tls-verify=true 2>&/dev/null
        oc get backupplans/"{{ trilio_kubernetes_backupplan_name_var }}" -n {{ trilio_kubernetes_namespace_var }}
      register: trilio_kubernetes_backupplan_available
      retries: "{{ trilio_kubernetes_backupplan_polling_retries }}"
      delay: "{{ trilio_kubernetes_backupplan_polling_every_seconds }}"
      until: trilio_kubernetes_backupplan_available.stdout.find("Available") != -1
      ignore_errors: true
      when:
        - trilio_kubernetes_auth_type == "password"
        - trilio_kubernetes_distro == "openshift"
        - trilio_kubernetes_cli | bool
      changed_when: trilio_kubernetes_backupplan_available.rc != 0

    - name: Show backup plan created output
      ansible.builtin.debug:
        var: trilio_kubernetes_backupplan_available.stdout_lines
